#cloud-config
disk_setup:
    /dev/vdb:
        table_type: gpt
        layout: [66, [33, 82]]
        overwrite: True
fs_setup:
    - device: /dev/vdb
      partition: 1
      filesystem: ext4
    - device: /dev/vdb
      partition: 2
      filesystem: swap
mounts:
    - ["/dev/vdb1", "/mnt"]
    - ["/dev/vdb2", "none", "swap", "sw", "0", "0"]
